apiVersion: v1
appVersion: v1.22.1
description: Create Kubernetes secrets from Vault for a secure GitOps based workflow.
home: https://github.com/ricoberger/vault-secrets-operator
icon: https://raw.githubusercontent.com/ricoberger/vault-secrets-operator/main/assets/logo.png
maintainers:
  - name: Rico Berger
    url: https://ricoberger.de
name: vault-secrets-operator
version: 2.5.1
